<h1>Welcome to the Sample ZF2 Bitcoin-PHP Library Application</h1>

<p>For sample code on how to use the ZF2 Module for the Bitcoin-PHP library in your application, take a look at the file <a href='IndexController.php.txt'>module/MyApp/Controller/IndexController.php</a>.</p>

<p>To include the ZF2 Module for Bitcoin-PHP library in your project, simply add the bitcoin-php module to your project's composer.json file. See the sample app's <a href='composer.json.txt'>composer.json</a> file.</p>


<h2>BitcoinClient::can_connect()</h2>
<pre>
<?=$this->can_connect?>
</pre>

<h2>BitcoinClient::help()</h2>
<pre>
<?=$this->help?>
</pre>